cmd: "$(pwd)/build.sh"
name: "Build script"
sh: true,
errorMatch:
  - "(?<file>[\\/0-9a-zA-Z\\.\\+_]+):(?<line>\\d+):(?<col>\\d+): error: (?<message>.+)"
warningMatch:
  - "(?<file>[\\/0-9a-zA-Z\\.\\+_]+):(?<line>\\d+):(?<col>\\d+): warning: (?<message>.+)"
targets:
  "Run Script":
    sh: true
    cmd: "$(pwd)/build.sh run"
  "Run in iTerm2":
    sh: true
    cmd: "runInLastITerm.sh \"pushd $(pwd); ./run.sh; popd\""
