os:
  - osx
language: generic
sudo: required
osx_image: xcode8.3
before_install:
  - brew update
install:
  - brew install llvm@3.9
script:
  - set -o pipefail
  - swift .build/checkouts/LLVMSwift.git-*/utils/make-pkgconfig.swift
  - swift build -Xcc -I/usr/local/opt/llvm/include -Xlinker -L/usr/local/opt/llvm/lib
